baseurl = "http://book.tonybai.com/"
languageCode = "zh_CN"
title = "Tony Bai的开源书栈"

theme = "hyde"

[params]
	description = "敏而好学，不耻写作"
	themeColor = "theme-base-08" # for hyde theme
	disqusShortname = "booktonybaicom"
